# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/mi/Desktop/lab5_cpu/lab5_cpu.srcs/sources_1/ip/InstructionMemory/InstructionMemory.xci
# IP: The module: 'InstructionMemory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mi/Desktop/lab5_cpu/lab5_cpu.srcs/sources_1/ip/InstructionMemory/InstructionMemory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'InstructionMemory'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/mi/Desktop/lab5_cpu/lab5_cpu.srcs/sources_1/ip/InstructionMemory/InstructionMemory.xci
# IP: The module: 'InstructionMemory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mi/Desktop/lab5_cpu/lab5_cpu.srcs/sources_1/ip/InstructionMemory/InstructionMemory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'InstructionMemory'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
